name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 3/336 * * 1"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"

    env:
      PACKAGE: teachopencadd

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.cfg.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install package
        run: |
          uv pip install --system -e "."

      - name: Test CLI
        run: |
          teachopencadd -h
          teachopencadd -l

      - name: Run unit tests
        run: |
          python -m pytest ${PACKAGE}/tests/ -v --color=yes


