name: Docs

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # every two weeks on Monday at 3 am
    - cron: "0 3/336 * * 1"

permissions:
  contents: write

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: teachopencadd

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install package and docs dependencies
        shell: bash -l {0}
        run: |
          mamba install -n teachopencadd -c conda-forge pandoc --yes
          uv pip install -e "."
          uv pip install sphinx sphinx_rtd_theme sphinx-gallery sphinx-material sphinx-copybutton sphinxext-opengraph "sphinx-autodoc-typehints<3.9" matplotlib ipywidgets nbsphinx nbsphinx-link ipython numpydoc "docutils<0.21"

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Run Sphinx
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-T --keep-going" make html

      - name: Check 404s (README)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          max-depth: 1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
